INSERT INTO public.trends (question, source, signal, score_novelty, score_payfit_relevance, score_volume, icp_target, suggested_format, status) VALUES
('Transparence des salaires 2026 : quelles obligations pour les employeurs ?', 'Directive UE 2023/970', 'Transposition avant juin 2026, fourchettes salariales obligatoires dans les offres', 5, 5, 5, 'ICP 2', 'Article pilier + FAQ', 'new'),
('Réduction générale dégressive unique (RGDU) : comment ça marche en 2026 ?', 'LFSS 2026', 'Remplacement des 3 anciens dispositifs, nouveau calcul', 5, 5, 4, 'ICP 2', 'Article technique + simulateur', 'new'),
('SMIC 2026 : montant, impact sur la paie et les cotisations', 'travail-emploi.gouv.fr', '12,02€ brut/h, 1823,03€ brut/mois, impact cascade cotisations', 4, 5, 5, 'ICP 1+2', 'Article + tableau récapitulatif', 'new'),
('Congé supplémentaire de naissance 2026 : droit, durée, impact paie', 'LFSS 2026', 'Nouveau congé créé par LFSS, naissances à compter du 1er janvier', 5, 4, 4, 'ICP 1+2', 'Article + guide pratique', 'new'),
('Rupture conventionnelle 2026 : hausse du forfait social à 40%', 'LFSS 2026', 'Passage de 30% à 40% du forfait social', 4, 5, 4, 'ICP 1+2', 'Article + calculateur intégré', 'new'),
('Plafond de la sécurité sociale 2026 : nouveaux montants et conséquences', 'Arrêté 22/12/2025', 'PMSS à 4005€ (+2%), impact cotisations', 3, 5, 4, 'ICP 2', 'Article technique', 'new'),
('Titres-restaurant 2026 : exonération, montant, règles employeur', 'URSSAF', 'Plafond exonération 7,32€, montants recommandés', 3, 4, 5, 'ICP 1+2', 'Article + tableau', 'new'),
('Versement mobilité régional et rural (VMRR) 2026 : nouvelles régions', 'DSN / URSSAF', 'Extension à de nouvelles régions au-delà Corse/Occitanie', 4, 3, 3, 'ICP 2', 'Article + carte régions', 'new'),
('Gratification de stage 2026 : nouveau montant et obligations', 'Code éducation', 'Passage à 4,50€/h (15% du PHSS)', 3, 3, 3, 'ICP 1+2', 'Article pratique', 'new'),
('Congés payés et arrêt maladie 2026 : nouvelles règles acquisition', 'Loi 22/04/2024', '2 jours ouvrables/mois en maladie non-pro, obligation info employeur', 4, 4, 4, 'ICP 2', 'Article juridique + FAQ', 'new'),
('Déduction forfaitaire heures supplémentaires 2026 : extension +250 salariés', 'LFSS 2026', 'Extension à toutes les entreprises, 0,50€/h pour +20 salariés', 4, 3, 3, 'ICP 2', 'Article + exemple chiffré', 'new'),
('Cotisation vieillesse déplafonnée 2026 : nouveau taux 2,11%', 'LFSS 2026', 'Hausse de 2,02% à 2,11%, impact coût employeur', 3, 4, 2, 'ICP 2', 'Article technique', 'new'),
('Bulletin de paie 2026 : modèle, mentions obligatoires, nouveautés', 'Code du travail', 'RGDU visible sur bulletin, net social maintenu', 3, 5, 5, 'ICP 1+2', 'Article + modèle téléchargeable', 'new'),
('Télétravail 2026 : allocation forfaitaire exonérée et barème', 'URSSAF', '2,70€/jour, 59,40€/mois max', 2, 3, 4, 'ICP 1+2', 'Article + tableau', 'new'),
('Avantages en nature 2026 : repas, logement, véhicule — barèmes', 'URSSAF', 'Repas 5,50€, logement barème progressif', 2, 4, 3, 'ICP 2', 'Article récapitulatif', 'new'),
('Chèques cadeaux CSE 2026 : plafond exonération 200€', 'URSSAF', '5% PMSS, règles par événement', 2, 3, 3, 'ICP 1+2', 'Article pratique', 'new'),
('DSN 2026 : nouvelles contributions sectorielles à déclarer', 'DSN-info', 'Dialogue social et formation pro de nouveaux secteurs en DSN', 3, 3, 2, 'ICP 2', 'Article technique', 'new'),
('IA et gestion de la paie : comment automatiser sans risque en 2026 ?', 'Tendance marché', 'IA pour détecter anomalies, vérifier conformité', 4, 4, 3, 'ICP 2', 'Article thought leadership', 'new'),
('Index égalité femmes-hommes 2026 : renforcement avec transparence salariale', 'Directive UE + Egapro', 'Articulation Index Egapro + directive transparence', 3, 3, 3, 'ICP 2', 'Article juridique', 'new'),
('Exonérations zones en difficulté économique 2026 : plafond à 25%', 'LFSS 2026', 'Nouveau plafonnement en ZFRR, BER, etc.', 3, 2, 2, 'ICP 2', 'Article technique', 'new');
